name: linter

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@main
        with:
          node-version: 18
          check-latest: true

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint
